version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    depends_on:
      - database
    working_dir: /opt/app
    volumes:
      - ./:/opt/app
    environment:
      DB_PORT: 3306
      DB_HOST: "database"

  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    command: [nginx-debug, '-g', 'daemon off;']

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 3306:3306
